---
# tasks file for install-all-packages
  - name: Add sublime to trusted 1
    ansible.builtin.shell:
      cmd: "wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null"
    tags:
      - sublime-text
    become: true
  - name: Add sublime to trusted 2
    ansible.builtin.shell:
      cmd: "echo 'deb https://download.sublimetext.com/ apt/stable/' | tee /etc/apt/sources.list.d/sublime-text.list"
    tags:
      - sublime-text
    become: true
  - name: Add sublime to trusted 3
    ansible.builtin.shell:
      cmd: "apt-get update"
    become: true
    tags:
      - sublime-text

  - name: Install sublime
    ansible.builtin.apt:
      name: 
        - sublime-text
        - sublime-merge
    tags:
      - sublime-text
    become: true
  - name: "Install all neccesary packages"
    apt:
      name: "{{apt_packages}}"
      state: latest
    tags:
      - packages
    become: true
